name: Unit testing
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: install modules
              run: npm install
            - name: build from ts
              run: npx tsc
            - name: run tests
              run: npm test